services:
  # Backend Web Service
  - type: web
    name: email-lead-sync-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: IMAP_HOST
        sync: false
      - key: IMAP_PORT
        sync: false
      - key: IMAP_SECURE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SUBJECT_PATTERN
        sync: false
      - key: FRONTEND_URL
        sync: false
