services:
  # Backend API Service
  - type: web
    name: email-lead-sync-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: IMAP_HOST
        sync: false
      - key: IMAP_PORT
        sync: false
      - key: IMAP_SECURE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SUBJECT_PATTERN
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend Static Site
  - type: web
    name: email-lead-sync-frontend
    env: static
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
